import { randomUUID } from "crypto";

type WebsiteConfig = Record<string, any>;
type ExtractedData = {
  profile?: {
    username?: string;
    fullName?: string;
    headline?: string;
    summary?: string;
    location?: string;
    profilePicture?: string;
    headerImage?: string;
    linkedinUrl?: string;
  };
};

function escapeHtml(input: string): string {
  return input
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function generateSimpleHtml(data: ExtractedData, config: WebsiteConfig): string {
  const profile = data.profile ?? {};
  const fullName = escapeHtml(profile.fullName || profile.username || "My Website");
  const headline = escapeHtml(profile.headline || "");
  const summary = escapeHtml(profile.summary || "");
  const location = escapeHtml(profile.location || "");
  const linkedinUrl = escapeHtml(profile.linkedinUrl || (profile.username ? `https://www.linkedin.com/in/${profile.username}` : ""));

  const primary = typeof config?.colorScheme?.primary === "string" ? config.colorScheme.primary : "#2563eb";
  const secondary = typeof config?.colorScheme?.secondary === "string" ? config.colorScheme.secondary : "#1e40af";
  const accent = typeof config?.colorScheme?.accent === "string" ? config.colorScheme.accent : "#60a5fa";

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${fullName}</title>
    <style>
      :root { --primary:${primary}; --secondary:${secondary}; --accent:${accent}; }
      body { font-family: system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif; margin:0; color:#0f172a; background:#fff; }
      header { background: linear-gradient(135deg, var(--primary), var(--secondary)); color:#fff; padding: 72px 24px; text-align:center; }
      h1 { margin:0 0 10px; font-size: clamp(28px, 4vw, 44px); }
      .headline { margin:0; opacity:.95; font-size: 18px; }
      main { max-width: 900px; margin: -28px auto 0; padding: 0 20px 80px; }
      .card { background:#fff; border:1px solid #e2e8f0; border-radius: 16px; box-shadow: 0 10px 30px rgba(15,23,42,.08); padding: 28px; }
      .meta { display:flex; gap:12px; flex-wrap:wrap; color:#475569; margin-top: 12px; }
      .btn { display:inline-flex; align-items:center; justify-content:center; gap:8px; background:var(--primary); color:#fff; text-decoration:none; padding: 12px 16px; border-radius: 10px; font-weight:600; }
      .btn:hover { filter: brightness(.95); }
      .section-title { margin: 0 0 12px; font-size: 18px; color:#0f172a; }
      .summary { white-space: pre-line; color:#334155; line-height: 1.8; }
      footer { text-align:center; padding: 28px 20px; color:#64748b; }
    </style>
  </head>
  <body>
    <header>
      <h1>${fullName}</h1>
      ${headline ? `<p class="headline">${headline}</p>` : ""}
    </header>
    <main>
      <div class="card">
        ${location ? `<div class="meta"><span>📍 ${location}</span></div>` : ""}
        <h2 class="section-title" style="margin-top:20px;">About</h2>
        ${summary ? `<div class="summary">${summary}</div>` : "<div class=\"summary\">Profile summary will appear here.</div>"}
        ${linkedinUrl ? `<div style="margin-top:22px;"><a class="btn" href="${linkedinUrl}" target="_blank" rel="noopener">View on LinkedIn</a></div>` : ""}
      </div>
    </main>
    <footer>Generated by Brand Weaver</footer>
  </body>
</html>`;
}

export const handler = async (event: any) => {
  if (event.httpMethod !== "POST") {
    return { statusCode: 405, body: "Method not allowed" };
  }

  const parsed = (() => {
    try {
      return JSON.parse(event.body || "{}") as Record<string, unknown>;
    } catch {
      return {} as Record<string, unknown>;
    }
  })();

  const data = (parsed.data ?? null) as ExtractedData | null;
  const config = (parsed.config ?? null) as WebsiteConfig | null;

  if (!data || !config) {
    return {
      statusCode: 400,
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ error: "data and config are required" }),
    };
  }

  const sessionId = randomUUID();
  const html = generateSimpleHtml(data, config);

  return {
    statusCode: 200,
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ sessionId, html }),
  };
};

export default { handler };

