import archiver from "archiver";
import type { Archiver } from "archiver";
import { storage } from "./storage";
import type { ExtractedData } from "@shared/schema";

export async function createZipArchive(): Promise<Archiver> {
  const archive = archiver("zip", {
    zlib: { level: 9 },
  });

  // Get latest extracted data from storage
  const extractedData = await storage.getLatestExtractedData();
  
  if (extractedData) {
    archive.append(JSON.stringify(extractedData, null, 2), { name: "profile-data.json" });
    archive.append(createReadme(extractedData), { name: "README.md" });
  } else {
    // Fallback to sample data
    const sampleData = getSampleData();
    archive.append(JSON.stringify(sampleData, null, 2), { name: "profile-data.json" });
    archive.append("# LinkedIn Profile Data\n\nExtracted profile data is in profile-data.json", { name: "README.md" });
  }

  return archive;
}

export async function createDataJson(): Promise<string> {
  // Get latest extracted data from storage
  const extractedData = await storage.getLatestExtractedData();
  
  if (extractedData) {
    return JSON.stringify(extractedData, null, 2);
  }

  // Fallback to sample data
  return JSON.stringify(getSampleData(), null, 2);
}

export async function createImagesArchive(): Promise<Archiver> {
  const archive = archiver("zip", {
    zlib: { level: 9 },
  });

  const extractedData = await storage.getLatestExtractedData();

  // Add a placeholder readme with information about what would be included
  const readme = `# Profile Images

This archive contains optimized profile images in WebP format.

${extractedData ? `
Profile: ${extractedData.profile.fullName}
Extracted: ${extractedData.extractedAt}

Images included:
- profile-picture.webp (if available)
- header-image.webp (if available)
- Company logos
- Recommender avatars
` : `
Note: In a live extraction with the RapidAPI key configured, this would contain:
- profile-picture.webp
- header-image.webp
- company logos
- recommender avatars

All images are converted to WebP format and optimized for web performance.
`}`;

  archive.append(readme, { name: "README.md" });

  return archive;
}

export async function createSourceArchive(): Promise<Archiver> {
  const archive = archiver("zip", {
    zlib: { level: 9 },
  });

  // Get generated website files
  const websiteFiles = await storage.getLatestGeneratedWebsite();
  const extractedData = await storage.getLatestExtractedData();
  
  if (websiteFiles) {
    websiteFiles.forEach((content, filename) => {
      archive.append(content, { name: filename });
    });
    
    // Add deployment instructions
    const deployReadme = createDeploymentReadme(extractedData);
    archive.append(deployReadme, { name: "DEPLOY.md" });
  } else {
    archive.append("<!-- Website not yet generated -->", { name: "index.html" });
    archive.append("# Source Code\n\nGenerate a website first to download the source code.", { name: "README.md" });
  }

  return archive;
}

function createDeploymentReadme(data: ExtractedData | null | undefined): string {
  const profileName = data?.profile?.fullName || "Your Portfolio";
  return `# Deployment Guide for ${profileName}

## GitHub Pages Deployment

### Option 1: Quick Setup
1. Create a new GitHub repository
2. Upload all files from this ZIP to the repository
3. Go to repository Settings > Pages
4. Under "Source", select "Deploy from a branch"
5. Select "main" branch and "/ (root)" folder
6. Click Save
7. Your site will be live at: https://YOUR-USERNAME.github.io/REPO-NAME

### Option 2: Using Git
\`\`\`bash
# Initialize repository
git init
git add .
git commit -m "Initial commit - Personal Brand Website"

# Create GitHub repository and push
gh repo create your-portfolio --public --source=.
git push -u origin main
\`\`\`

## Netlify Deployment
1. Go to https://app.netlify.com
2. Drag and drop this folder to deploy
3. Your site will be live immediately

## Vercel Deployment
1. Go to https://vercel.com
2. Import your GitHub repository or drag and drop files
3. Your site will be deployed with automatic SSL

## Custom Domain Setup

### GitHub Pages
1. Add a CNAME file with your domain name
2. Configure DNS:
   - A record: @ -> 185.199.108.153
   - A record: @ -> 185.199.109.153
   - A record: @ -> 185.199.110.153
   - A record: @ -> 185.199.111.153
   - CNAME record: www -> YOUR-USERNAME.github.io

### Netlify
1. Add domain in Site settings > Domain management
2. Configure DNS with CNAME to your-site.netlify.app

### Vercel
1. Add domain in Project Settings > Domains
2. Configure DNS with CNAME to cname.vercel-dns.com

---
Generated by Brand Weaver - LinkedIn to Personal Brand Website Tool
`;
}

function createReadme(data: ExtractedData): string {
  return `# LinkedIn Profile Data

## ${data.profile.fullName}
${data.profile.headline || ''}

**Location:** ${data.profile.location || 'Not specified'}
**LinkedIn:** ${data.profile.linkedinUrl}

## Contents

- **profile-data.json** - Complete extracted profile data in JSON format

## Stats

- Work Experience: ${data.experience.length} positions
- Education: ${data.education.length} entries
- Certifications: ${data.certifications.length}
- Skills: ${data.skills.length}
- Languages: ${data.languages.length}
- Recommendations: ${data.recommendations.length}
- Featured Posts: ${data.featuredPosts.length}

## Extracted On
${data.extractedAt}

---
Generated by LinkedIn to Personal Brand Website Tool
`;
}

function getSampleData() {
  return {
    profile: {
      username: "sample-user",
      fullName: "John Doe",
      headline: "Senior Software Engineer",
      summary: "Passionate software engineer with 8+ years of experience building scalable web applications.",
      location: "San Francisco Bay Area",
      linkedinUrl: "https://linkedin.com/in/sample-user",
    },
    experience: [
      {
        id: "exp-1",
        title: "Senior Software Engineer",
        company: "Tech Innovations Inc.",
        location: "San Francisco, CA",
        startDate: "2021-03",
        isCurrent: true,
        description: "Leading development of cloud-native applications.",
      },
    ],
    education: [
      {
        id: "edu-1",
        school: "Massachusetts Institute of Technology",
        degree: "Master of Science",
        fieldOfStudy: "Computer Science",
        startDate: "2014",
        endDate: "2016",
      },
    ],
    certifications: [
      {
        id: "cert-1",
        name: "AWS Solutions Architect Professional",
        issuer: "Amazon Web Services",
        issueDate: "2023-01",
      },
    ],
    skills: [
      { name: "JavaScript", endorsements: 42 },
      { name: "TypeScript", endorsements: 38 },
      { name: "React", endorsements: 35 },
    ],
    languages: [
      { name: "English", proficiency: "Native" },
      { name: "Spanish", proficiency: "Professional" },
    ],
    recommendations: [
      {
        id: "rec-1",
        recommenderName: "Sarah Johnson",
        recommenderHeadline: "VP of Engineering",
        text: "John is an exceptional engineer with great leadership skills.",
      },
    ],
    extractedAt: new Date().toISOString(),
  };
}
